In [51]:
pip install faker

Requirement already satisfied: faker in /usr/local/lib/python3.11/dist-packages (36.1.1)
Requirement already satisfied: tzdata in /usr/local/lib/python3.11/dist-packages (from faker) (2025.1)

In [52]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [53]:
pip install numpy

Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (1.26.4)

In [54]:
from faker import Faker
import pandas as pd
import numpy as np
import random

In [55]:
fake = Faker()

In [84]:
tranDate = []
custName = []
cardNum = []
zipCode = []
tranAmount = []
prodId = []
prodCate = []
brand = []
starRate = []
prodColor = []
size = []
mrp = []
sellPrice = []
discount = []
custId = []
quant = []
orderId = []
age = []
city = []

brand_names = [ "Adidas", "Puma", "Reebok", "Under Armour", "Levi's", "Gucci", "Prada", "Zara", "H&M"]


product_categories = [
    "Tops", "Dresses", "Bottoms", "Outerwear", "Lingerie"
]

size_options = {
    "Tops": ["S", "M", "L", "XL", "XXL"],
    "Dresses": ["S", "M", "L", "XL", "XXL"],
    "Bottoms": ["S", "M", "L", "XL", "XXL"],
    "Outerwear": ["S", "M", "L", "XL", "XXL", "XS", "XXXL"],
    "Lingerie": ["S", "M", "L", "XL", "XXL"]
}

mrp_ranges = {
      "Zara": (500, 4000),
      "H&M": (400, 3000),
      "Gucci": (800, 4000),
      "Prada": (500, 3000),  # Added
      "Reebok": (800, 4000),   # Added
      "Under Armour": (2500, 3000),  # Added
      "Adidas": (500, 4000),  # Added
      "Puma": (600, 3000),     # Added
      "Levi's": (400, 2000)    # Added
}


def get_discount(mrp):
    if mrp > 5000:
        return 5  # 5% discount
    elif mrp > 3000:
        return 4  # 4% discount
    elif mrp > 1000:
        return 3  # 3% discount
    else:
        return 2

In [85]:
def dummy_data(numRec):
    for _ in range(numRec):
        tranDate.append(fake.date_time_between_dates('-1y', 'now'))
    for _ in range(numRec):
        custName.append(fake.name())
    for _ in range(numRec):
        cardNum.append(fake.credit_card_number())
    for _ in range(numRec):
        zipCode.append(fake.zipcode())

    for _ in range(numRec):
        prodId.append(fake.random.randint(101, 500))
    for _ in range(numRec):
        prodCate.append(random.choice(product_categories))

    for _ in range(numRec):
        selected_brand = random.choice(list(mrp_ranges.keys()))  # Ensure brand exists in mrp_ranges
        brand.append(selected_brand)

    for _ in range(numRec):
        starRate.append(fake.random.randint(1, 5))
    for _ in range(numRec):
        prodColor.append(fake.color_name())
    for _ in range(numRec):
        category = random.choice(product_categories)
        size.append(random.choice(size_options[category]))

    for _ in range(numRec):
      selected_brand = random.choice(list(mrp_ranges.keys()))  # Ensure brand exists in mrp_ranges
      brand.append(selected_brand)
      min_mrp, max_mrp = mrp_ranges[selected_brand]  # Fetch correct MRP range
      item_mrp = random.randint(min_mrp, max_mrp)
      mrp.append(item_mrp)  # Store the generated MRP for each record

    for i in range(numRec):
      discount_percent = get_discount(mrp[i])  # Get discount for the individual MRP
      discount.append(discount_percent)

    for i in range(numRec):
      item_sell_price = mrp[i] - (mrp[i] * discount[i] / 100)  # Use the individual MRP and discount
      sellPrice.append(round(item_sell_price, 2))  # Store the calculated sell price


    for _ in range(numRec):
        custId.append(fake.random.randint(1, 5000))

    for _ in range(numRec):
        quant.append(fake.random.randint(1, 10))
    for _ in range(numRec):
        orderId.append(fake.random.randint(1, 500))
    for _ in range(numRec):
        age.append(fake.random.randint(15, 70))
    for _ in range(numRec):
        city.append(fake.city())

    for i in range(numRec):
        final_amount = sellPrice[i] * quant[i]
        tranAmount.append(round(final_amount, 2))

In [86]:
tranDate = []
custName = []
cardNum = []
zipCode = []
tranAmount = []
prodId = []
prodCate = []
brand = []
starRate = []
prodColor = []
size = []
mrp = []
sellPrice = []
discount = []
custId = []
quant = []
orderId = []
age = []
city = []

dummy_data(30000)
df = pd.DataFrame(

    zip(custId,custName,age,city,zipCode,orderId,tranDate,cardNum,prodId,prodCate,prodColor,
        brand,size,quant,starRate,mrp,discount,sellPrice,tranAmount),
    columns=['custId','custName','age','city','zipCode','orderId','tranDate','cardNum','prodId','prodCate',
             'prodColor','brand','size','quant','starRate','mrp','discount','sellPrice','tranAmount']

)
df.shape

(30000, 19)

In [87]:
df

,custId,custName,age,city,zipCode,orderId,tranDate,cardNum,prodId,prodCate,prodColor,brand,size,quant,starRate,mrp,discount,sellPrice,tranAmount
0,1920,Julie Berry,18,Riosmouth,48095,425,2024-03-07 13:53:07.475868,342318551529574,119,Bottoms,Aqua,Zara,XXL,10,3,2003,3,1942.91,19429.10
1,1138,Rachel Jones,25,West Leah,67706,393,2024-11-02 02:48:26.772721,213102378647892,229,Dresses,LightGray,Levi's,L,9,4,623,2,610.54,5494.86
2,4362,Michael Parsons,18,Lake Tina,91635,296,2024-08-10 12:43:40.579135,3504269441742950,160,Dresses,Peru,Gucci,M,2,4,1143,3,1108.71,2217.42
3,1529,Kara Thompson,66,Graceside,63801,87,2024-10-05 06:56:39.675940,584361292991,252,Outerwear,Yellow,Puma,M,3,3,1985,3,1925.45,5776.35
4,53,Christian Walters,58,New Lonnie,75370,479,2024-05-28 01:05:44.227163,4194822547520172969,214,Tops,Ivory,Adidas,L,2,1,1927,3,1869.19,3738.38
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,1761,Charles Russo,65,New Joseph,70881,298,2024-11-13 09:07:58.942441,30225256029528,463,Bottoms,LightGoldenRodYellow,Puma,L,4,4,1195,3,1159.15,4636.60
29996,4390,Danielle Lane,16,Port Eddiebury,98585,151,2024-05-24 18:07:31.891094,4947091401498384237,278,Dresses,LightYellow,Adidas,M,10,1,1526,3,1480.22,14802.20
29997,1314,Joseph Robinson,52,East Mollyport,48262,43,2024-07-23 18:26:44.560408,675975685750,454,Bottoms,SlateBlue,Adidas,L,9,2,2066,3,2004.02,18036.18
29998,3080,Michael Brown,25,Amyshire,62674,455,2024-02-15 11:44:36.609338,2229498897018542,391,Dresses,Chartreuse,H&M,XL,5,5,795,2,779.10,3895.50
29999,1468,Whitney Mitchell,53,Greenetown,33429,405,2024-05-14 09:33:28.323516,30452332522900,177,Bottoms,Navy,Levi's,M,9,4,2445,3,2371.65,21344.85

In [88]:
df.to_csv('dummy_data.csv', index=False)

from google.colab import files
files.download('dummy_data.csv')